language: node_js
sudo: required
node_js:
- "10"
cache:
  yarn: true
  directories:
  - node_modules
  - "$HOME/google-cloud-sdk/"
before_install:
- brew install git-lfs
- openssl aes-256-cbc -K $encrypted_4e43db931be4_key -iv $encrypted_4e43db931be4_iv -in deployments.tar.enc -out deployments.tar -d
- tar xvf deployments.tar
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash > /dev/null; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud components install kubectl || true
- git lfs install
- git lfs pull
install:
- yarn install
- yarn lint
deploy:
- provider: script
  skip_cleanup: true
  script: bash ./deploy.sh production
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: bash ./deploy.sh staging
  on:
    branch: staging
