const LANDINGPAGE_ACTION = {
  GET_FAQ_CONTENT: 'GET_FAQ_CONTENT',
  GET_USER_AGREEMENT_CONTENT: 'GET_USER_AGREEMENT_CONTENT',
  GET_PRIVACY_CONTENT: 'GET_PRIVACY_CONTENT',
};

export default LANDINGPAGE_ACTION;
