const LANDINGPAGE_ACTION = {
  GET_ABOUT_CONTENT: 'GET_ABOUT_CONTENT',
  GET_FAQ_CONTENT: 'GET_FAQ_CONTENT',
  GET_USER_AGREEMENT_CONTENT: 'GET_USER_AGREEMENT_CONTENT',
  GET_PRIVACY_CONTENT: 'GET_PRIVACY_CONTENT',
  GET_PROMOTION_CONTENT: 'GET_PROMOTION_CONTENT',
  GET_HOW_IT_WORKS_CONTENT: 'GET_HOW_IT_WORKS_CONTENT',
};

export default LANDINGPAGE_ACTION;
