export default {
  AD: 'AD - Andorra',
  AE: 'AE - UAE',
  AF: 'AF - Afghanistan',
  AG: 'AG - Antigua & Barbuda',
  AI: 'AI - Anguilla',
  AL: 'AL - Albania',
  AM: 'AM - Armenia',
  AN: 'AN - Netherland Antilles',
  AO: 'AO - Angola',
  AR: 'AR - Argentina',
  AS: 'AS - American Samoa',
  AT: 'AT - Austria',
  AU: 'AU - Australia',
  AW: 'AW - Aruba',
  AZ: 'AZ - Azerbaijan',
  BA: 'BA - Bosnia & Herzegovina',
  BB: 'BB - Barbados',
  BC: 'BC - BIOT',
  BD: 'BD - Bangladesh',
  BE: 'BE - Belgium',
  BF: 'BF - Burkina Faso',
  BG: 'BG - Bulgaria',
  BH: 'BH - Bahrain',
  BI: 'BI - Burundi',
  BJ: 'BJ - Benin',
  BL: 'BL - Bonaire',
  BM: 'BM - Bermuda',
  BN: 'BN - Brunei',
  BO: 'BO - Bolivia',
  BR: 'BR - Brazil',
  BS: 'BS - Bahamas',
  BT: 'BT - Bhutan',
  BW: 'BW - Botswana',
  BY: 'BY - Belarus',
  BZ: 'BZ - Belize',
  CA: 'CA - Canada',
  CB: 'CB - Curacao',
  CC: 'CC - Cocos Island',
  CD: 'CD - Channel Islands',
  CF: 'CF - CAR',
  CG: 'CG - Congo',
  CH: 'CH - Switzerland',
  CI: 'CI - Cote D"Ivoire',
  CK: 'CK - Cook Islands',
  CL: 'CL - Chile',
  CM: 'CM - Cameroon',
  CN: 'CN - China',
  CO: 'CO - Colombia',
  CR: 'CR - Costa Rica',
  CU: 'CU - Cuba',
  CV: 'CV - Cape Verde',
  CX: 'CX - Christmas Island',
  CY: 'CY - Cyprus',
  CZ: 'CZ - Czech Republic',
  DE: 'DE - Germany',
  DJ: 'DJ - Djibouti',
  DK: 'DK - Denmark',
  DM: 'DM - Dominica',
  DO: 'DO - Dominican Republic',
  DZ: 'DZ - Algeria',
  EC: 'EC - Ecuador',
  EE: 'EE - Estonia',
  EG: 'EG - Egypt',
  ER: 'ER - Eritrea',
  ES: 'ES - Spain',
  ET: 'ET - Ethiopia',
  EU: 'EU - St Eustatius',
  FI: 'FI - Finland',
  FJ: 'FJ - Fiji',
  FK: 'FK - Falkland Islands',
  FO: 'FO - Faroe Islands',
  FR: 'FR - France',
  GA: 'GA - Gabon',
  GB: 'GB - United Kingdom',
  GD: 'GD - Grenada',
  GE: 'GE - Georgia',
  GF: 'GF - French Guiana',
  GH: 'GH - Ghana',
  GI: 'GI - Gibraltar',
  GL: 'GL - Greenland',
  GM: 'GM - Gambia',
  GN: 'GN - Guinea',
  GP: 'GP - Guadeloupe',
  GQ: 'GQ - Equatorial Guinea',
  GR: 'GR - Greece',
  GT: 'GT - Guatemala',
  GU: 'GU - Guam',
  GY: 'GY - Guyana',
  HE: 'HE - St Helena',
  HK: 'HK - Hong Kong',
  HN: 'HN - Honduras',
  HR: 'HR - Croatia',
  HT: 'HT - Haiti',
  HU: 'HU - Hungary',
  HW: 'HW - Hawaii',
  IA: 'IA - Iran',
  IC: 'IC - Canary Islands',
  ID: 'ID - Indonesia',
  IL: 'IL - Israel',
  IM: 'IM - Isle of Man',
  IN: 'IN - India',
  IQ: 'IQ - Iraq',
  IR: 'IR - Ireland',
  IS: 'IS - Iceland',
  IT: 'IT - Italy',
  JM: 'JM - Jamaica',
  JO: 'JO - Jordan',
  JP: 'JP - Japan',
  KE: 'KE - Kenya',
  KG: 'KG - Kyrgyzstan',
  KH: 'KH - Cambodia',
  KI: 'KI - Kiribati',
  KM: 'KM - Comoros',
  KN: 'KN - St Kitts-Nevis',
  KS: 'KS - Korea South',
  KW: 'KW - Kuwait',
  KY: 'KY - Cayman Islands',
  KZ: 'KZ - Kazakhstan',
  LA: 'LA - Laos',
  LB: 'LB - Lebanon',
  LC: 'LC - St Lucia',
  LI: 'LI - Liechtenstein',
  LK: 'LK - Sri Lanka',
  LR: 'LR - Liberia',
  LS: 'LS - Lesotho',
  LT: 'LT - Lithuania',
  LU: 'LU - Luxembourg',
  LV: 'LV - Latvia',
  LY: 'LY - Libya',
  MA: 'MA - Morocco',
  MB: 'MB - St Maarten',
  MC: 'MC - Monaco',
  MD: 'MD - Moldova',
  ME: 'ME - Montenegro',
  MG: 'MG - Madagascar',
  MH: 'MH - Marshall Islands',
  MI: 'MI - Midway Islands',
  MK: 'MK - Macedonia',
  ML: 'ML - Mali',
  MM: 'MM - Myanmar',
  MN: 'MN - Mongolia',
  MO: 'MO - Macau',
  MQ: 'MQ - Martinique',
  MR: 'MR - Mauritania',
  MS: 'MS - Montserrat',
  MT: 'MT - Malta',
  MU: 'MU - Mauritius',
  MV: 'MV - Maldives',
  MW: 'MW - Malawi',
  MX: 'MX - Mexico',
  MY: 'MY - Malaysia',
  MZ: 'MZ - Mozambique',
  NA: 'NA - Nambia',
  NC: 'NC - New Caledonia',
  NE: 'NE - Niger',
  NF: 'NF - Norfolk Island',
  NG: 'NG - Nigeria',
  NI: 'NI - Nicaragua',
  NK: 'NK - Korea North',
  NL: 'NL - Netherlands',
  NO: 'NO - Norway',
  NP: 'NP - Nepal',
  NT: 'NT - St Barthelemy',
  NU: 'NU - Nauru',
  NV: 'NV - Nevis',
  NW: 'NW - Niue',
  NZ: 'NZ - New Zealand',
  OI: 'OI - Somalia',
  OM: 'OM - Oman',
  PA: 'PA - Panama',
  PE: 'PE - Peru',
  PF: 'PF - French Polynesia',
  PG: 'PG - Papua New Guinea',
  PH: 'PH - Philippines',
  PK: 'PK - Pakistan',
  PL: 'PL - Poland',
  PM: 'PM - St Pierre',
  PO: 'PO - Pitcairn Island',
  PR: 'PR - Puerto Rico',
  PS: 'PS - Palestine',
  PT: 'PT - Portugal',
  PW: 'PW - Palau Island',
  PY: 'PY - Paraguay',
  QA: 'QA - Qatar',
  RE: 'RE - Reunion',
  RO: 'RO - Romania',
  RS: 'RS - Serbia',
  RW: 'RW - Rwanda',
  SA: 'SA - Saudi Arabia',
  SB: 'SB - Solomon Islands',
  SC: 'SC - Seychelles',
  SD: 'SD - Sudan',
  SE: 'SE - Sweden',
  SG: 'SG - Singapore',
  SI: 'SI - Slovenia',
  SK: 'SK - Slovakia',
  SL: 'SL - Sierra Leone',
  SM: 'SM - San Marino',
  SN: 'SN - Senegal',
  SP: 'SP - Saipan',
  SR: 'SR - Suriname',
  ST: 'ST - Sao Tome',
  SV: 'SV - El Salvador',
  SY: 'SY - Syria',
  SZ: 'SZ - Swaziland',
  TA: 'TA - Tahiti',
  TC: 'TC - Turks & Caicos Is',
  TD: 'TD - Chad',
  TF: 'TF - French Southern Ter',
  TG: 'TG - Togo',
  TH: 'TH - Thailand',
  TJ: 'TJ - Tajikistan',
  TK: 'TK - Tokelau',
  TM: 'TM - East Timor',
  TN: 'TN - Tunisia',
  TO: 'TO - Tonga',
  TR: 'TR - Turkey',
  TT: 'TT - Trinidad & Tobago',
  TU: 'TU - Turkmenistan',
  TV: 'TV - Tuvalu',
  TW: 'TW - Taiwan',
  TZ: 'TZ - Tanzania',
  UA: 'UA - Ukraine',
  UG: 'UG - Uganda',
  US: 'US - U.S.',
  USAL: 'USAL - U.S - Alaska',
  USH: 'USH - U.S - Hawaii',
  USPR: 'USPR - U.S - Puerto Rico',
  UY: 'UY - Uruguay',
  UZ: 'UZ - Uzbekistan',
  VA: 'VA - Virgin Islands (USA)',
  VB: 'VB - Virgin Islands (Brit)',
  VC: 'VC - St Vincent',
  VE: 'VE - Venezuela',
  VN: 'VN - Vietnam',
  VS: 'VS - Vatican City State',
  VU: 'VU - Vanuatu',
  WF: 'WF - Wallis & Futana Is',
  WK: 'WK - Wake Island',
  WS: 'WS - Samoa',
  YE: 'YE - Yemen',
  YT: 'YT - Mayotte',
  ZA: 'ZA - South Africa',
  ZM: 'ZM - Zambia',
  ZR: 'ZR - Zaire',
  ZW: 'ZW - Zimbabwe'
};

export const DEFAULT_COUNTRY = 'HK';
