export const FIAT_CURRENCY = {
  RUB: 'RUB',
  VND: 'VND',
  PHP: 'PHP',
  CAD: 'CAD',
  USD: 'USD',
  EUR: 'EUR',
  HKD: 'HKD',
};

export const FIAT_CURRENCY_NAME = {
  [FIAT_CURRENCY.RUB]: 'RUB',
  [FIAT_CURRENCY.VND]: 'VND',
  [FIAT_CURRENCY.PHP]: 'PHP',
  [FIAT_CURRENCY.CAD]: 'CAD',
  [FIAT_CURRENCY.USD]: 'USD',
  [FIAT_CURRENCY.EUR]: 'EUR',
  [FIAT_CURRENCY.HKD]: 'HKD',
};

export const FIAT_CURRENCY_LIST = [
  { id: FIAT_CURRENCY.RUB, text: FIAT_CURRENCY_NAME[FIAT_CURRENCY.RUB] },
  { id: FIAT_CURRENCY.VND, text: FIAT_CURRENCY_NAME[FIAT_CURRENCY.VND] },
  { id: FIAT_CURRENCY.PHP, text: FIAT_CURRENCY_NAME[FIAT_CURRENCY.PHP] },
  { id: FIAT_CURRENCY.CAD, text: FIAT_CURRENCY_NAME[FIAT_CURRENCY.CAD] },
  { id: FIAT_CURRENCY.USD, text: FIAT_CURRENCY_NAME[FIAT_CURRENCY.USD] },
  { id: FIAT_CURRENCY.EUR, text: FIAT_CURRENCY_NAME[FIAT_CURRENCY.EUR] },
  { id: FIAT_CURRENCY.HKD, text: FIAT_CURRENCY_NAME[FIAT_CURRENCY.HKD] },
];
